#!/bin/bash

### BEGIN INIT INFO
# Provides:          odoo17
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Odoo17 daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PATH=/opt/odoo17/:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/odoo17/odoo-bin
NAME=odoo17
DESC=odoo17
USER=odoo17

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC"
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
      --chuid $USER --background --make-pidfile \
      --exec $DAEMON -- --config /etc/odoo17.conf
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC"
    start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
      --retry 10
    log_end_msg $?
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting $DESC"
    start-stop-daemon --stop --quiet --pidfile \
      /var/run/$NAME.pid --retry 10
    start-stop-daemon --start --quiet --pidfile \
      /var/run/$NAME.pid --chuid $USER --background \
      --make-pidfile --exec $DAEMON -- --config /etc/odoo17.conf
    log_end_msg $?
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
